### ISSUE TITLE
feat: implement custom tags input component

### ISSUE THREAD

**Issue by chankruze** [chankruze/react-components#2]
Just like the example (inspiration from YouTube)

![image](https://user-images.githubusercontent.com/29806845/170857815-811067d4-6422-45a0-879c-bb142a8c6e95.png)

**Tasks**

- [x] create a very basic UI to `add` and `remove` tag
- [x] add `copy` and `clear all` buttons
- [x] #4
- [ ] implement logic to count no. of characters
- [ ] restrict the user to enter a certain amount of characters (maybe per tag or overall)

**Comment by chankruze** [comment]
**Task 3**

![image](https://user-images.githubusercontent.com/29806845/170866377-10fd0bf1-168e-4d29-96a1-1c632e220ae9.png)

Instead of adding as plain text, parse the pasted string and tokenize the tags. Use `,` as default delimiter.
